name: dist_perf_analytics
version: '1.0'
config-version: 2

profile: snowflake_dbt

target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  dist_perf_analytics:
    staging:
      materialized: view
    marts:
      materialized: table