name: dist_perf_analytics
version: '1.0'
config-version: 2

profile: snowflake_dbt

target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  dist_perf_analytics:
    marts:
      +schema: dist_perf_analytics  # materialize mart/analytics models into the analytics schema
      +materialized: table
    staging:
      +schema: dist_perf_staging    # materialize staging models into the staging schema
      materialized: view
