name: dist_perf_analytics
version: '1.0'
config-version: 2

profile: snowflake_dbt

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analysis"]
target-path: "target"
log-path: "logs"
clean-targets: ["target", "dbt_packages"]

models:
  dist_perf_analytics:
    marts:
      +schema: dist_perf_analytics  # materialize mart/analytics models into the analytics schema
      +materialized: table
    staging:
      +schema: dist_perf_staging    # materialize staging models into the staging schema
      +materialized: view
